# Generated by Django 4.1.2 on 2023-03-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_alter_post_post_pic_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='cancle',
            field=models.BooleanField(default=False),
        ),
    ]
